# Generated by Django 5.0.7 on 2024-08-25 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_name", models.CharField(max_length=500)),
                ("username", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="P1ASOCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("year", models.IntegerField(default=0)),
                ("topic", models.CharField(max_length=50)),
                ("marks", models.IntegerField(default=0)),
                ("img", models.ImageField(default="", upload_to="img")),
                ("img_ans", models.ImageField(default="", upload_to="img_ans")),
                ("guidance", models.CharField(default="Not Set", max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name="P2ASOCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("year", models.IntegerField(default=0)),
                ("topic", models.CharField(max_length=50)),
                ("marks", models.IntegerField(default=0)),
                ("img", models.ImageField(default="", upload_to="img")),
                ("img_ans", models.ImageField(default="", upload_to="img_ans")),
                ("guidance", models.CharField(default="Not Set", max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="pdfs/")),
                ("username", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("no_of_likes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Pwdlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionP1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("year", models.IntegerField(default=0)),
                ("topic", models.CharField(max_length=50)),
                ("marks", models.IntegerField(default=0)),
                ("img", models.ImageField(default="", upload_to="img")),
                ("prompt", models.CharField(default="Not Set", max_length=250)),
                ("ans", models.CharField(default="Not Set", max_length=5250)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionP2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("year", models.IntegerField(default=0)),
                ("topic", models.CharField(max_length=50)),
                ("marks", models.IntegerField(default=0)),
                ("img", models.ImageField(default="", upload_to="img")),
                ("prompt", models.CharField(default="Not Set", max_length=250)),
                ("ans", models.CharField(default="Not Set", max_length=5250)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionP3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0)),
                ("year", models.IntegerField(default=0)),
                ("topic", models.CharField(max_length=50)),
                ("marks", models.IntegerField(default=0)),
                ("img", models.ImageField(default="", upload_to="img")),
                ("prompt", models.CharField(default="Not Set", max_length=250)),
                ("ans", models.CharField(default="Not Set", max_length=5250)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.IntegerField()),
                ("bio", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("premium", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
