# Generated by Django 5.0.7 on 2024-08-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="p1asocr",
            name="img_w",
            field=models.ImageField(default="", upload_to="img_w"),
        ),
        migrations.AddField(
            model_name="p2asocr",
            name="img_w",
            field=models.ImageField(default="", upload_to="img_w"),
        ),
    ]
